<a href="https://colab.research.google.com/github/RaniellyPatricia/predicao-abandono-escolar-mg/blob/main/notebooks/01_coleta_e_descricao.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Coleta e Descrição dos Dados

## Predição do Abandono Escolar nos Municípios de Minas Gerais

Este notebook tem como objetivo realizar a leitura inicial, a identificação da estrutura e a descrição das bases públicas do INEP utilizadas no projeto.

Nesta etapa ainda não serão aplicados filtros nem tratamentos definitivos. Primeiro serão verificadas as abas, colunas, dimensões, tipos de dados, valores ausentes e possíveis duplicidades.

## 1. Nível Socioeconômico — INSE

Nesta seção será realizada a inspeção inicial da base municipal do Indicador de Nível Socioeconômico de 2023.

Serão analisadas a estrutura da planilha, as abas disponíveis, as dimensões, as colunas, os tipos de dados, os valores ausentes e possíveis duplicidades. Nesta etapa, a base ainda não será filtrada ou modificada.

In [6]:
import pandas as pd
import requests
from io import BytesIO

url_inse = (
    "https://raw.githubusercontent.com/"
    "RaniellyPatricia/predicao-abandono-escolar-mg/"
    "main/data/raw/2023/inse/INSE_2023_municipios.xlsx"
)

resposta = requests.get(url_inse)
resposta.raise_for_status()

print("Tamanho baixado:", len(resposta.content), "bytes")
print("Assinatura do arquivo:", resposta.content[:4])

arquivo_inse = pd.ExcelFile(BytesIO(resposta.content))

arquivo_inse.sheet_names

Tamanho baixado: 11483563 bytes
Assinatura do arquivo: b'PK\x03\x04'

['INSE_MUN_2023', 'Dicionário']

In [7]:
df_inse = pd.read_excel(
    BytesIO(resposta.content),
    sheet_name="INSE_MUN_2023"
)

print("Quantidade de linhas:", df_inse.shape[0])
print("Quantidade de colunas:", df_inse.shape[1])

df_inse.head()

Quantidade de linhas: 125741
Quantidade de colunas: 19

,NU_ANO_SAEB,CO_UF,SG_UF,NO_UF,CO_MUNICIPIO,NO_MUNICIPIO,TP_TIPO_REDE,TP_LOCALIZACAO,TP_CAPITAL,QTD_ALUNOS_INSE,MEDIA_INSE,PC_NIVEL_1,PC_NIVEL_2,PC_NIVEL_3,PC_NIVEL_4,PC_NIVEL_5,PC_NIVEL_6,PC_NIVEL_7,PC_NIVEL_8
0,2023,11,RO,Rondônia,1100122,Ji-Paraná,2,1,2,3258,5.0083,0.16,6.71,18.43,25.63,24.64,14.36,9.18,0.89
1,2023,11,RO,Rondônia,1101559,Teixeirópolis,0,2,2,19,4.8242,5.26,NaN,21.05,31.58,26.32,15.79,NaN,NaN
2,2023,11,RO,Rondônia,1100205,Porto Velho,3,1,1,3610,4.8843,0.57,11.59,20.00,26.07,20.78,12.87,7.11,1.02
3,2023,11,RO,Rondônia,1101005,Governador Jorge Teixeira,5,2,2,46,4.8115,0.00,6.59,21.59,39.09,19.77,8.64,4.32,NaN
4,2023,11,RO,Rondônia,1100205,Porto Velho,2,1,1,9541,5.0505,0.30,7.89,17.27,23.41,23.09,16.37,10.45,1.23

In [8]:
print("Colunas da base INSE:")

for coluna in df_inse.columns:
    print(coluna)
df_inse.dtypes

Colunas da base INSE:
NU_ANO_SAEB
CO_UF
SG_UF
NO_UF
CO_MUNICIPIO
NO_MUNICIPIO
TP_TIPO_REDE
TP_LOCALIZACAO
TP_CAPITAL
QTD_ALUNOS_INSE
MEDIA_INSE
PC_NIVEL_1
PC_NIVEL_2
PC_NIVEL_3
PC_NIVEL_4
PC_NIVEL_5
PC_NIVEL_6
PC_NIVEL_7
PC_NIVEL_8

NU_ANO_SAEB          int64
CO_UF                int64
SG_UF               object
NO_UF               object
CO_MUNICIPIO         int64
NO_MUNICIPIO        object
TP_TIPO_REDE         int64
TP_LOCALIZACAO       int64
TP_CAPITAL           int64
QTD_ALUNOS_INSE      int64
MEDIA_INSE         float64
PC_NIVEL_1         float64
PC_NIVEL_2         float64
PC_NIVEL_3         float64
PC_NIVEL_4         float64
PC_NIVEL_5         float64
PC_NIVEL_6         float64
PC_NIVEL_7         float64
PC_NIVEL_8         float64
dtype: object

In [9]:
resumo_nulos_inse = pd.DataFrame({
    "quantidade_nulos": df_inse.isna().sum(),
    "percentual_nulos": (df_inse.isna().mean() * 100).round(2)
})

resumo_nulos_inse

                 quantidade_nulos  percentual_nulos
NU_ANO_SAEB                     0              0.00
CO_UF                           0              0.00
SG_UF                           0              0.00
NO_UF                           0              0.00
CO_MUNICIPIO                    0              0.00
NO_MUNICIPIO                    0              0.00
TP_TIPO_REDE                    0              0.00
TP_LOCALIZACAO                  0              0.00
TP_CAPITAL                      0              0.00
QTD_ALUNOS_INSE                 0              0.00
MEDIA_INSE                    890              0.71
PC_NIVEL_1                     85              0.07
PC_NIVEL_2                   4460              3.55
PC_NIVEL_3                   1612              1.28
PC_NIVEL_4                    520              0.41
PC_NIVEL_5                    774              0.62
PC_NIVEL_6                   2950              2.35
PC_NIVEL_7                   7811              6.21
PC_NIVEL_8                  42414             33.73

In [10]:
quantidade_duplicadas_inse = df_inse.duplicated().sum()
print("Quantidade de linhas duplicadas:", quantidade_duplicadas_inse)

Quantidade de linhas duplicadas: 54165

In [11]:
registros_duplicados_inse = df_inse[
    df_inse.duplicated(keep=False)
].copy()

print(
    "Total de registros envolvidos em duplicidades:",
    registros_duplicados_inse.shape[0]
)

registros_duplicados_inse.head(10)

Total de registros envolvidos em duplicidades: 63034

,NU_ANO_SAEB,CO_UF,SG_UF,NO_UF,CO_MUNICIPIO,NO_MUNICIPIO,TP_TIPO_REDE,TP_LOCALIZACAO,TP_CAPITAL,QTD_ALUNOS_INSE,MEDIA_INSE,PC_NIVEL_1,PC_NIVEL_2,PC_NIVEL_3,PC_NIVEL_4,PC_NIVEL_5,PC_NIVEL_6,PC_NIVEL_7,PC_NIVEL_8
0,2023,11,RO,Rondônia,1100122,Ji-Paraná,2,1,2,3258,5.0083,0.16,6.71,18.43,25.63,24.64,14.36,9.18,0.89
2,2023,11,RO,Rondônia,1100205,Porto Velho,3,1,1,3610,4.8843,0.57,11.59,20.00,26.07,20.78,12.87,7.11,1.02
4,2023,11,RO,Rondônia,1100205,Porto Velho,2,1,1,9541,5.0505,0.30,7.89,17.27,23.41,23.09,16.37,10.45,1.23
10,2023,11,RO,Rondônia,1100072,Corumbiara,3,2,2,26,4.8232,0.00,3.92,19.17,53.38,15.69,3.92,NaN,3.92
12,2023,11,RO,Rondônia,1100015,Alta Floresta D'Oeste,2,1,2,480,4.9806,0.23,10.35,17.03,24.31,23.10,13.52,10.14,1.31
14,2023,11,RO,Rondônia,1100122,Ji-Paraná,2,1,2,3258,5.0083,0.16,6.71,18.43,25.63,24.64,14.36,9.18,0.89
16,2023,11,RO,Rondônia,1100205,Porto Velho,2,1,1,9541,5.0505,0.30,7.89,17.27,23.41,23.09,16.37,10.45,1.23
18,2023,11,RO,Rondônia,1100122,Ji-Paraná,2,1,2,3258,5.0083,0.16,6.71,18.43,25.63,24.64,14.36,9.18,0.89
19,2023,11,RO,Rondônia,1100049,Cacoal,2,1,2,1813,5.0218,0.28,7.32,17.01,26.28,23.55,15.89,8.88,0.80
22,2023,11,RO,Rondônia,1100015,Alta Floresta D'Oeste,3,1,2,240,5.0306,0.00,6.27,17.54,29.45,23.42,14.68,7.19,1.45

In [12]:
frequencia_duplicatas_inse = (
    df_inse
    .value_counts(dropna=False)
    .reset_index(name="FREQUENCIA")
)

frequencia_duplicatas_inse = frequencia_duplicatas_inse[
    frequencia_duplicatas_inse["FREQUENCIA"] > 1
].sort_values(
    by="FREQUENCIA",
    ascending=False
)

frequencia_duplicatas_inse.head(10)

,NU_ANO_SAEB,CO_UF,SG_UF,NO_UF,CO_MUNICIPIO,NO_MUNICIPIO,TP_TIPO_REDE,TP_LOCALIZACAO,TP_CAPITAL,QTD_ALUNOS_INSE,MEDIA_INSE,PC_NIVEL_1,PC_NIVEL_2,PC_NIVEL_3,PC_NIVEL_4,PC_NIVEL_5,PC_NIVEL_6,PC_NIVEL_7,PC_NIVEL_8,FREQUENCIA
0,2023,35,SP,São Paulo,3550308,São Paulo,2,1,1,171332,5.1512,0.41,5.48,13.23,23.64,25.28,18.60,12.21,1.14,1121
1,2023,33,RJ,Rio de Janeiro,3304557,Rio de Janeiro,3,1,1,80160,4.8607,0.88,10.09,20.30,28.19,21.73,11.77,6.36,0.69,947
2,2023,35,SP,São Paulo,3550308,São Paulo,3,1,1,70814,5.0653,0.65,6.97,14.78,24.69,24.80,16.73,10.45,0.93,552
3,2023,53,DF,Distrito Federal,5300108,Brasília,2,1,1,61528,5.3384,0.27,4.10,10.14,19.73,24.48,20.55,17.85,2.88,480
4,2023,29,BA,Bahia,2927408,Salvador,3,1,1,16910,4.5461,2.23,18.67,27.55,27.48,14.55,5.96,3.09,0.47,287
5,2023,23,CE,Ceará,2304400,Fortaleza,3,1,1,35105,4.5944,1.28,17.64,27.50,27.26,15.59,7.19,3.25,0.29,281
6,2023,13,AM,Amazonas,1302603,Manaus,3,1,1,28542,4.8092,0.87,12.89,22.07,26.57,19.35,10.73,6.60,0.92,271
7,2023,33,RJ,Rio de Janeiro,3304557,Rio de Janeiro,2,1,1,28238,4.8396,1.27,11.95,19.51,26.72,21.05,12.05,6.77,0.67,248
8,2023,13,AM,Amazonas,1302603,Manaus,2,1,1,42619,4.9518,0.73,10.81,18.96,24.70,20.30,12.97,10.01,1.53,223
9,2023,26,PE,Pernambuco,2611606,Recife,3,1,1,11171,4.6294,1.17,14.47,28.41,29.33,16.48,6.81,3.00,0.34,217

### Diagnóstico das duplicidades

Foram encontradas 54.165 ocorrências duplicadas, considerando como duplicada toda linha idêntica a uma ocorrência anterior.

No total, 63.034 registros estão envolvidos em grupos de duplicidade. Após considerar apenas uma ocorrência de cada linha, a base possui 71.576 registros únicos.

Algumas linhas apresentam frequência muito elevada, chegando a 1.121 repetições de um mesmo registro.

Como todas as 19 variáveis são idênticas nesses casos, as ocorrências foram classificadas como duplicidades exatas. A remoção será realizada posteriormente, na etapa de pré-processamento, mantendo a base original inalterada.

In [13]:
df_inse_tratado = df_inse.copy()

df_inse_tratado = df_inse_tratado[
    df_inse_tratado["SG_UF"] == "MG"
].copy()

print("Linhas da base original:", len(df_inse))
print("Linhas de Minas Gerais:", len(df_inse_tratado))

df_inse_tratado.head()

Linhas da base original: 125741
Linhas de Minas Gerais: 14671

,NU_ANO_SAEB,CO_UF,SG_UF,NO_UF,CO_MUNICIPIO,NO_MUNICIPIO,TP_TIPO_REDE,TP_LOCALIZACAO,TP_CAPITAL,QTD_ALUNOS_INSE,MEDIA_INSE,PC_NIVEL_1,PC_NIVEL_2,PC_NIVEL_3,PC_NIVEL_4,PC_NIVEL_5,PC_NIVEL_6,PC_NIVEL_7,PC_NIVEL_8
56381,2023,31,MG,Minas Gerais,3137007,Ladainha,5,0,2,393,4.4330,5.05,25.98,23.45,19.31,16.10,6.89,2.95,0.26
56382,2023,31,MG,Minas Gerais,3137007,Ladainha,6,1,2,276,4.3366,6.23,28.93,24.16,17.19,15.47,5.91,1.73,0.37
56383,2023,31,MG,Minas Gerais,3137007,Ladainha,5,1,2,276,4.3366,6.23,28.93,24.16,17.19,15.47,5.91,1.73,0.37
56384,2023,31,MG,Minas Gerais,3137007,Ladainha,5,2,2,117,4.6678,2.16,18.78,21.73,24.46,17.65,9.29,5.93,NaN
56385,2023,31,MG,Minas Gerais,3137007,Ladainha,3,2,2,117,4.6678,2.16,18.78,21.73,24.46,17.65,9.29,5.93,NaN

In [14]:
linhas_antes = len(df_inse_tratado)

df_inse_tratado = df_inse_tratado.drop_duplicates().copy()

linhas_depois = len(df_inse_tratado)

print("Linhas antes:", linhas_antes)
print("Linhas depois:", linhas_depois)
print("Duplicidades removidas:", linhas_antes - linhas_depois)

Linhas antes: 14671
Linhas depois: 10249
Duplicidades removidas: 4422

In [15]:
df_inse_tratado = df_inse_tratado[
    (df_inse_tratado["TP_TIPO_REDE"]== 6) &
    (df_inse_tratado["TP_LOCALIZACAO"] == 0)
].copy()

print("Quantidade de linhas:", len(df_inse_tratado))
print(
    "Quantidade de municípios únicos:",
    df_inse_tratado["CO_MUNICIPIO"].nunique()
)

df_inse_tratado.head()

Quantidade de linhas: 853
Quantidade de municípios únicos: 853

,NU_ANO_SAEB,CO_UF,SG_UF,NO_UF,CO_MUNICIPIO,NO_MUNICIPIO,TP_TIPO_REDE,TP_LOCALIZACAO,TP_CAPITAL,QTD_ALUNOS_INSE,MEDIA_INSE,PC_NIVEL_1,PC_NIVEL_2,PC_NIVEL_3,PC_NIVEL_4,PC_NIVEL_5,PC_NIVEL_6,PC_NIVEL_7,PC_NIVEL_8
56403,2023,31,MG,Minas Gerais,3136959,Juvenília,6,0,2,228,4.4254,3.26,25.15,24.13,25.74,12.28,5.66,3.34,0.43
56409,2023,31,MG,Minas Gerais,3136900,Juruaia,6,0,2,306,5.1850,0.00,3.58,13.73,21.87,27.45,22.13,11.25,NaN
56487,2023,31,MG,Minas Gerais,3136702,Juiz de Fora,6,0,2,9283,5.1931,0.36,5.39,12.72,22.98,24.92,17.76,14.11,1.76
56546,2023,31,MG,Minas Gerais,3136652,Juatuba,6,0,2,966,5.1363,0.65,5.44,13.82,23.05,25.62,19.53,10.34,1.55
56553,2023,31,MG,Minas Gerais,3136603,Nova União,6,0,2,191,5.0039,0.47,7.72,15.65,25.26,25.55,16.88,8.47,NaN

In [16]:
print(
    "Valores ausentes em MEDIA_INSE:",
    df_inse_tratado["MEDIA_INSE"].isna().sum()
)

print(
    "Percentual de valores ausentes:",
    round(df_inse_tratado["MEDIA_INSE"].isna().mean() * 100, 2),
    "%"
)

Valores ausentes em MEDIA_INSE: 0
Percentual de valores ausentes: 0.0 %

In [17]:
df_inse_final = df_inse_tratado[
    [
        "NU_ANO_SAEB",
        "CO_MUNICIPIO",
        "NO_MUNICIPIO",
        "QTD_ALUNOS_INSE",
        "MEDIA_INSE"
    ]
].copy()

df_inse_final = df_inse_final.rename(
    columns={"NU_ANO_SAEB": "ANO"}
)

df_inse_final.head()

        ANO  CO_MUNICIPIO  NO_MUNICIPIO  QTD_ALUNOS_INSE  MEDIA_INSE
56403  2023       3136959     Juvenília              228      4.4254
56409  2023       3136900       Juruaia              306      5.1850
56487  2023       3136702  Juiz de Fora             9283      5.1931
56546  2023       3136652       Juatuba              966      5.1363
56553  2023       3136603    Nova União              191      5.0039

In [18]:
df_inse_final.to_csv(
    "inse_mg_2023_tratado.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Arquivo salvo com sucesso.")

Arquivo salvo com sucesso.

In [19]:
from google.colab import files

files.download("inse_mg_2023_tratado.csv")

## 2. Taxa de Distorção Idade-Série — TDI

Nesta seção será realizada a leitura, inspeção e preparação da base da Taxa de Distorção Idade-Série de 2023.

A base original será preservada sem alterações. O tratamento será realizado em uma cópia dos dados, considerando o recorte dos municípios de Minas Gerais e do Ensino Fundamental — Anos Finais.

In [20]:
url_tdi = (
    "https://raw.githubusercontent.com/"
    "RaniellyPatricia/predicao-abandono-escolar-mg/"
    "main/data/raw/2023/tdi/TDI_MUNICIPIOS_2023.xlsx"
)

resposta_tdi = requests.get(url_tdi)
resposta_tdi.raise_for_status()

print("Tamanho baixado:", len(resposta_tdi.content), "bytes")
print("Assinatura do arquivo:", resposta_tdi.content[:4])

arquivo_tdi = pd.ExcelFile(BytesIO(resposta_tdi.content))

arquivo_tdi.sheet_names

Tamanho baixado: 8071174 bytes
Assinatura do arquivo: b'PK\x03\x04'

['MUNICIPIO']

In [21]:
df_tdi = pd.read_excel(
    BytesIO(resposta_tdi.content),
    sheet_name="MUNICIPIO",
    header=8
)

print("Quantidade de linhas:", df_tdi.shape[0])
print("Quantidade de colunas:", df_tdi.shape[1])

df_tdi.head()

Quantidade de linhas: 65574
Quantidade de colunas: 24

,NU_ANO_CENSO,NO_REGIAO,SG_UF,CO_MUNICIPIO,NO_MUNICIPIO,NO_CATEGORIA,NO_DEPENDENCIA,FUN_CAT_0,FUN_AI_CAT_0,FUN_AF_CAT_0,...,FUN_05_CAT_0,FUN_06_CAT_0,FUN_07_CAT_0,FUN_08_CAT_0,FUN_09_CAT_0,MED_CAT_0,MED_01_CAT_0,MED_02_CAT_0,MED_03_CAT_0,MED_04_CAT_0
0,2023,Norte,RO,1100015.0,Alta Floresta D'Oeste,Total,Total,12.7,7.8,17.5,...,11.9,12.4,17.8,16.5,23.2,17.3,20.2,18,10.6,--
1,2023,Norte,RO,1100015.0,Alta Floresta D'Oeste,Urbana,Total,8.9,4.2,13.4,...,6.1,8.1,12.3,13.6,19.6,12.6,13.2,13.3,10.6,--
2,2023,Norte,RO,1100015.0,Alta Floresta D'Oeste,Rural,Total,30.8,24.5,37.3,...,39.3,34.9,39.7,33.3,40,98.1,97.4,100,--,--
3,2023,Norte,RO,1100015.0,Alta Floresta D'Oeste,Total,Estadual,20.1,38,17.8,...,32.1,12.4,18.6,16.3,23.8,17.3,20.2,18,10.6,--
4,2023,Norte,RO,1100015.0,Alta Floresta D'Oeste,Urbana,Estadual,11.1,0,11.4,...,0,5.6,11.8,11.7,16.7,12.6,13.2,13.3,10.6,--

In [22]:
df_tdi_tratado = df_tdi[
    df_tdi["SG_UF"] == "MG"
].copy()

print("Linhas da base original:", len(df_tdi))
print("Linhas de Minas Gerais:", len(df_tdi_tratado))
print(
    "Municípios únicos:",
    df_tdi_tratado["CO_MUNICIPIO"].nunique()
)

Linhas da base original: 65574
Linhas de Minas Gerais: 9473
Municípios únicos: 853

In [23]:
print("Valores de NO_CATEGORIA:")
print(df_tdi_tratado["NO_CATEGORIA"].dropna().unique())

print("\nValores de NO_DEPENDENCIA:")
print(df_tdi_tratado["NO_DEPENDENCIA"].dropna().unique())

Valores de NO_CATEGORIA:
['Total' 'Urbana' 'Rural']

Valores de NO_DEPENDENCIA:
['Total' 'Estadual' 'Municipal' 'Pública' 'Privada' 'Federal']

In [24]:
df_tdi_tratado = df_tdi_tratado[
    (df_tdi_tratado["NO_CATEGORIA"] == "Total") &
    (df_tdi_tratado["NO_DEPENDENCIA"] == "Pública")
].copy()

print("Quantidade de linhas:", len(df_tdi_tratado))
print(
    "Quantidade de municípios únicos:",
    df_tdi_tratado["CO_MUNICIPIO"].nunique()
)

Quantidade de linhas: 853
Quantidade de municípios únicos: 853

In [25]:
print(
    "Valores ausentes em FUN_AF_CAT_0:",
    df_tdi_tratado["FUN_AF_CAT_0"].isna().sum()
)

print(
    "Tipo da coluna:",
    df_tdi_tratado["FUN_AF_CAT_0"].dtype
)

df_tdi_tratado[
    ["CO_MUNICIPIO", "NO_MUNICIPIO", "FUN_AF_CAT_0"]
].head()

Valores ausentes em FUN_AF_CAT_0: 0
Tipo da coluna: object

       CO_MUNICIPIO         NO_MUNICIPIO FUN_AF_CAT_0
28397     3100104.0  Abadia dos Dourados         11.4
28410     3100203.0               Abaeté         14.2
28422     3100302.0           Abre Campo         15.9
28435     3100401.0              Acaiaca           11
28447     3100500.0              Açucena         11.3

In [26]:
df_tdi_tratado['FUN_AF_CAT_0'] = pd.to_numeric(
    df_tdi_tratado['FUN_AF_CAT_0'],
    errors='coerce'
)
print("Novo tipo:", df_tdi_tratado["FUN_AF_CAT_0"].dtype)
print("Valores ausentes:", df_tdi_tratado["FUN_AF_CAT_0"].isna().sum())
print("Menor TDI:", df_tdi_tratado["FUN_AF_CAT_0"].min())
print("Maior TDI:", df_tdi_tratado["FUN_AF_CAT_0"].max())

Novo tipo: float64
Valores ausentes: 0
Menor TDI: 0.7
Maior TDI: 42.2

In [27]:
df_tdi_final = df_tdi_tratado[
    [
        "NU_ANO_CENSO",
        "CO_MUNICIPIO",
        "NO_MUNICIPIO",
        "FUN_AF_CAT_0"
    ]
].copy()

df_tdi_final = df_tdi_final.rename(
    columns={
        "NU_ANO_CENSO": "ANO",
        "FUN_AF_CAT_0": "TDI_ANOS_FINAIS"
    }
)

print("Quantidade de linhas:", len(df_tdi_final))
print(
    "Municípios duplicados:",
    df_tdi_final["CO_MUNICIPIO"].duplicated().sum()
)

df_tdi_final.head()

Quantidade de linhas: 853
Municípios duplicados: 0

        ANO  CO_MUNICIPIO         NO_MUNICIPIO  TDI_ANOS_FINAIS
28397  2023     3100104.0  Abadia dos Dourados             11.4
28410  2023     3100203.0               Abaeté             14.2
28422  2023     3100302.0           Abre Campo             15.9
28435  2023     3100401.0              Acaiaca             11.0
28447  2023     3100500.0              Açucena             11.3

In [28]:
df_tdi_final["CO_MUNICIPIO"] = (
    df_tdi_final["CO_MUNICIPIO"].astype("int64")
)

df_tdi_final.to_csv(
    "tdi_mg_2023_tratado.csv",
    index=False,
    encoding="utf-8-sig"
)

print(df_tdi_final.dtypes)

ANO                 object
CO_MUNICIPIO         int64
NO_MUNICIPIO        object
TDI_ANOS_FINAIS    float64
dtype: object

In [29]:
files.download("tdi_mg_2023_tratado.csv")

## 3. Média de Alunos por Turma — MAT

Nesta seção será realizada a leitura, inspeção e preparação da base de Média de Alunos por Turma de 2023.

A base original será preservada sem alterações. O tratamento será realizado em uma cópia dos dados, considerando o recorte dos municípios de Minas Gerais e do Ensino Fundamental — Anos Finais.

In [31]:
url_mat = (
    "https://raw.githubusercontent.com/"
    "RaniellyPatricia/predicao-abandono-escolar-mg/"
    "main/data/raw/2023/mat/ATU_MUNICIPIOS_2023.xlsx"
)

resposta_mat = requests.get(url_mat)
resposta_mat.raise_for_status()

print("Tamanho baixado:", len(resposta_mat.content), "bytes")
print("Assinatura do arquivo:", resposta_mat.content[:4])

arquivo_mat = pd.ExcelFile(BytesIO(resposta_mat.content))

arquivo_mat.sheet_names

Tamanho baixado: 9830455 bytes
Assinatura do arquivo: b'PK\x03\x04'

['MUNICIPIO']

In [32]:
df_mat = pd.read_excel(
    BytesIO(resposta_mat.content),
    sheet_name="MUNICIPIO",
    header=8
)
print("Quantidade de linhas:", df_mat.shape[0])
print("Quantidade de colunas:", df_mat.shape[1])

df_mat.head()

In [33]:
print("Colunas da base MAT:")

for coluna in df_mat.columns:
    print(coluna)

Colunas da base MAT:
NU_ANO_CENSO
NO_REGIAO
SG_UF
CO_MUNICIPIO
NO_MUNICIPIO
NO_CATEGORIA
NO_DEPENDENCIA
ED_INF_CAT_0
CRE_CAT_0
PRE_CAT_0
FUN_CAT_0
FUN_AI_CAT_0
FUN_AF_CAT_0
FUN_01_CAT_0
FUN_02_CAT_0
FUN_03_CAT_0
FUN_04_CAT_0
FUN_05_CAT_0
FUN_06_CAT_0
FUN_07_CAT_0
FUN_08_CAT_0
FUN_09_CAT_0
MULT_ETA_CAT_0
MED_CAT_0
MED_01_CAT_0
MED_02_CAT_0
MED_03_CAT_0
MED_04_CAT_0
MED_NS_CAT_0

In [34]:
df_mat_tratado = df_mat[
    df_mat["SG_UF"] == "MG"
].copy()

print("Linhas da base original:", len(df_mat))
print("Linhas de Minas Gerais:", len(df_mat_tratado))
print(
    "Municípios únicos:",
    df_mat_tratado["CO_MUNICIPIO"].nunique()
)

Linhas da base original: 66339
Linhas de Minas Gerais: 9647
Municípios únicos: 853

In [35]:
print("Valores de NO_CATEGORIA:")
print(df_mat_tratado["NO_CATEGORIA"].dropna().unique())

print("\nValores de NO_DEPENDENCIA:")
print(df_mat_tratado["NO_DEPENDENCIA"].dropna().unique())

Valores de NO_CATEGORIA:
['Total' 'Urbana' 'Rural']

Valores de NO_DEPENDENCIA:
['Total' 'Estadual' 'Municipal' 'Pública' 'Privada' 'Federal']

In [38]:
df_mat_tratado = df_mat_tratado[
    (df_mat_tratado["NO_CATEGORIA"] == "Total") &
    (df_mat_tratado["NO_DEPENDENCIA"] == "Pública")
].copy()

print("Quantidade de linhas:", len(df_mat_tratado))
print(
    "Quantidade de municípios únicos:",
    df_mat_tratado["CO_MUNICIPIO"].nunique()
)

Quantidade de linhas: 853
Quantidade de municípios únicos: 853

In [39]:
print(
    "Valores ausentes em FUN_AF_CAT_0:",
    df_mat_tratado["FUN_AF_CAT_0"].isna().sum()
)

print(
    "Tipo da coluna:",
    df_mat_tratado["FUN_AF_CAT_0"].dtype
)

df_mat_tratado[
    ["CO_MUNICIPIO", "NO_MUNICIPIO", "FUN_AF_CAT_0"]
].head()

Valores ausentes em FUN_AF_CAT_0: 0
Tipo da coluna: object

       CO_MUNICIPIO         NO_MUNICIPIO FUN_AF_CAT_0
28534     3100104.0  Abadia dos Dourados         33.1
28547     3100203.0               Abaeté         25.2
28560     3100302.0           Abre Campo         23.1
28573     3100401.0              Acaiaca         19.8
28586     3100500.0              Açucena         14.6

In [40]:
df_mat_tratado["FUN_AF_CAT_0"] = pd.to_numeric(
    df_mat_tratado["FUN_AF_CAT_0"],
    errors="coerce"
)

print("Novo tipo:", df_mat_tratado["FUN_AF_CAT_0"].dtype)
print("Valores ausentes:", df_mat_tratado["FUN_AF_CAT_0"].isna().sum())
print("Menor média de alunos por turma:", df_mat_tratado["FUN_AF_CAT_0"].min())
print("Maior média de alunos por turma:", df_mat_tratado["FUN_AF_CAT_0"].max())

Novo tipo: float64
Valores ausentes: 0
Menor média de alunos por turma: 7.0
Maior média de alunos por turma: 36.9

In [41]:
df_mat_final = df_mat_tratado[
    [
        "NU_ANO_CENSO",
        "CO_MUNICIPIO",
        "NO_MUNICIPIO",
        "FUN_AF_CAT_0"
    ]
].copy()

df_mat_final = df_mat_final.rename(
    columns={
        "NU_ANO_CENSO": "ANO",
        "FUN_AF_CAT_0": "MEDIA_ALUNOS_TURMA_ANOS_FINAIS"
    }
)

df_mat_final["CO_MUNICIPIO"] = df_mat_final["CO_MUNICIPIO"].astype("int64")

print("Quantidade de linhas:", len(df_mat_final))
print(
    "Municípios duplicados:",
    df_mat_final["CO_MUNICIPIO"].duplicated().sum()
)

df_mat_final.head()

Quantidade de linhas: 853
Municípios duplicados: 0

        ANO  CO_MUNICIPIO         NO_MUNICIPIO  MEDIA_ALUNOS_TURMA_ANOS_FINAIS
28534  2023       3100104  Abadia dos Dourados                            33.1
28547  2023       3100203               Abaeté                            25.2
28560  2023       3100302           Abre Campo                            23.1
28573  2023       3100401              Acaiaca                            19.8
28586  2023       3100500              Açucena                            14.6

In [42]:
print("Anos encontrados:", df_mat_final["ANO"].unique())

print("\nValores ausentes por coluna:")
print(df_mat_final.isna().sum())

print("\nRegistro de Frutal:")
df_mat_final[
    df_mat_final["NO_MUNICIPIO"].str.upper() == "FRUTAL"
]

Anos encontrados: [2023]

Valores ausentes por coluna:
ANO                               0
CO_MUNICIPIO                      0
NO_MUNICIPIO                      0
MEDIA_ALUNOS_TURMA_ANOS_FINAIS    0
dtype: int64

Registro de Frutal:

        ANO  CO_MUNICIPIO NO_MUNICIPIO  MEDIA_ALUNOS_TURMA_ANOS_FINAIS
31961  2023       3127107       Frutal                            26.2

In [43]:
df_mat_final.to_csv(
    "mat_mg_2023_tratado.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Arquivo salvo com sucesso.")

Arquivo salvo com sucesso.

In [46]:
files.download("mat_mg_2023_tratado.csv")

## 4. Regularidade do Corpo Docente — RCD

Nesta seção será realizada a leitura, inspeção e preparação da base do Indicador de Regularidade Docente de 2023.

A base original será preservada sem alterações. O tratamento será realizado em uma cópia dos dados, considerando o recorte dos municípios de Minas Gerais e o indicador municipal de regularidade docente.

In [47]:
url_rcd = (
    "https://raw.githubusercontent.com/"
    "RaniellyPatricia/predicao-abandono-escolar-mg/"
    "main/data/raw/2023/rcd/IRD_MUNICIPIOS_2023.xlsx"
)

resposta_rcd = requests.get(url_rcd)
resposta_rcd.raise_for_status()

print("Tamanho baixado:", len(resposta_rcd.content), "bytes")
print("Assinatura do arquivo:", resposta_rcd.content[:4])

arquivo_rcd = pd.ExcelFile(BytesIO(resposta_rcd.content))

arquivo_rcd.sheet_names

Tamanho baixado: 3526284 bytes
Assinatura do arquivo: b'PK\x03\x04'

['MUNICÍPIOS']

In [50]:
df_rcd = pd.read_excel(
    BytesIO(resposta_rcd.content),
    sheet_name="MUNICÍPIOS",
    header=9
)

print("Quantidade de linhas:", df_rcd.shape[0])
print("Quantidade de colunas:", df_rcd.shape[1])

df_rcd.head()

Quantidade de linhas: 66788
Quantidade de colunas: 11

,NU_ANO_CENSO,NO_REGIAO,SG_UF,CO_MUNICIPIO,NO_MUNICIPIO,NO_CATEGORIA,NO_DEPENDENCIA,EDU_BAS_CAT_1,EDU_BAS_CAT_2,EDU_BAS_CAT_3,EDU_BAS_CAT_4
0,2023,Norte,RO,1100015.0,Alta Floresta D'Oeste,Total,Total,3.7,25.9,44.4,26.0
1,2023,Norte,RO,1100015.0,Alta Floresta D'Oeste,Urbana,Total,6.3,37.5,50.0,6.2
2,2023,Norte,RO,1100015.0,Alta Floresta D'Oeste,Rural,Total,0.0,9.1,36.4,54.5
3,2023,Norte,RO,1100015.0,Alta Floresta D'Oeste,Total,Estadual,0.0,16.7,50.0,33.3
4,2023,Norte,RO,1100015.0,Alta Floresta D'Oeste,Urbana,Estadual,0.0,40.0,60.0,0.0

In [51]:
print("Colunas da base RCD:")

for coluna in df_rcd.columns:
    print(coluna)

Colunas da base RCD:
NU_ANO_CENSO
NO_REGIAO
SG_UF
CO_MUNICIPIO
NO_MUNICIPIO
NO_CATEGORIA
NO_DEPENDENCIA
EDU_BAS_CAT_1
EDU_BAS_CAT_2
EDU_BAS_CAT_3
EDU_BAS_CAT_4

In [52]:
df_rcd_tratado = df_rcd[
    df_rcd["SG_UF"] == "MG"
].copy()

print("Linhas da base original:", len(df_rcd))
print("Linhas de Minas Gerais:", len(df_rcd_tratado))
print(
    "Municípios únicos:",
    df_rcd_tratado["CO_MUNICIPIO"].nunique()
)

Linhas da base original: 66788
Linhas de Minas Gerais: 9759
Municípios únicos: 853

In [53]:
print("Valores de NO_CATEGORIA:")
print(df_rcd_tratado["NO_CATEGORIA"].dropna().unique())

print("\nValores de NO_DEPENDENCIA:")
print(df_rcd_tratado["NO_DEPENDENCIA"].dropna().unique())

Valores de NO_CATEGORIA:
['Total' 'Urbana' 'Rural']

Valores de NO_DEPENDENCIA:
['Total' 'Estadual' 'Municipal' 'Pública' 'Privada' 'Federal']

In [54]:
df_rcd_tratado = df_rcd_tratado[
    (df_rcd_tratado["NO_CATEGORIA"] == "Total") &
    (df_rcd_tratado["NO_DEPENDENCIA"] == "Pública")
].copy()

print("Quantidade de linhas:", len(df_rcd_tratado))
print(
    "Quantidade de municípios únicos:",
    df_rcd_tratado["CO_MUNICIPIO"].nunique()
)

Quantidade de linhas: 853
Quantidade de municípios únicos: 853

In [55]:
colunas_rcd = [
    "EDU_BAS_CAT_1",
    "EDU_BAS_CAT_2",
    "EDU_BAS_CAT_3",
    "EDU_BAS_CAT_4"
]

print("Valores ausentes:")
print(df_rcd_tratado[colunas_rcd].isna().sum())

print("\nTipos das colunas:")
print(df_rcd_tratado[colunas_rcd].dtypes)

df_rcd_tratado[
    ["CO_MUNICIPIO", "NO_MUNICIPIO"] + colunas_rcd
].head()

Valores ausentes:
EDU_BAS_CAT_1    0
EDU_BAS_CAT_2    0
EDU_BAS_CAT_3    0
EDU_BAS_CAT_4    0
dtype: int64

Tipos das colunas:
EDU_BAS_CAT_1    float64
EDU_BAS_CAT_2    float64
EDU_BAS_CAT_3    float64
EDU_BAS_CAT_4    float64
dtype: object

,CO_MUNICIPIO,NO_MUNICIPIO,EDU_BAS_CAT_1,EDU_BAS_CAT_2,EDU_BAS_CAT_3,EDU_BAS_CAT_4
28361,3100104.0,Abadia dos Dourados,0.0,14.3,28.6,57.1
28374,3100203.0,Abaeté,6.7,13.3,66.7,13.3
28387,3100302.0,Abre Campo,0.0,14.3,57.1,28.6
28400,3100401.0,Acaiaca,0.0,20.0,40.0,40.0
28413,3100500.0,Açucena,0.0,35.7,57.1,7.2

In [56]:
df_rcd_tratado["SOMA_RCD"] = (
    df_rcd_tratado["EDU_BAS_CAT_1"] +
    df_rcd_tratado["EDU_BAS_CAT_2"] +
    df_rcd_tratado["EDU_BAS_CAT_3"] +
    df_rcd_tratado["EDU_BAS_CAT_4"]
)

print("Menor soma:", df_rcd_tratado["SOMA_RCD"].min())
print("Maior soma:", df_rcd_tratado["SOMA_RCD"].max())

df_rcd_tratado[
    ["CO_MUNICIPIO", "NO_MUNICIPIO", "SOMA_RCD"]
].head()

Menor soma: 99.99999999999999
Maior soma: 100.00000000000001

       CO_MUNICIPIO         NO_MUNICIPIO  SOMA_RCD
28361     3100104.0  Abadia dos Dourados     100.0
28374     3100203.0               Abaeté     100.0
28387     3100302.0           Abre Campo     100.0
28400     3100401.0              Acaiaca     100.0
28413     3100500.0              Açucena     100.0

In [57]:
df_rcd_final = df_rcd_tratado[
    [
        "NU_ANO_CENSO",
        "CO_MUNICIPIO",
        "NO_MUNICIPIO",
        "EDU_BAS_CAT_1",
        "EDU_BAS_CAT_4"
    ]
].copy()

df_rcd_final = df_rcd_final.rename(
    columns={
        "NU_ANO_CENSO": "ANO",
        "EDU_BAS_CAT_1": "PERC_DOCENTES_BAIXA_REGULARIDADE",
        "EDU_BAS_CAT_4": "PERC_DOCENTES_ALTA_REGULARIDADE"
    }
)

df_rcd_final["CO_MUNICIPIO"] = df_rcd_final["CO_MUNICIPIO"].astype("int64")

print("Quantidade de linhas:", len(df_rcd_final))
print(
    "Municípios duplicados:",
    df_rcd_final["CO_MUNICIPIO"].duplicated().sum()
)

df_rcd_final.head()

Quantidade de linhas: 853
Municípios duplicados: 0

,ANO,CO_MUNICIPIO,NO_MUNICIPIO,PERC_DOCENTES_BAIXA_REGULARIDADE,PERC_DOCENTES_ALTA_REGULARIDADE
28361,2023,3100104,Abadia dos Dourados,0.0,57.1
28374,2023,3100203,Abaeté,6.7,13.3
28387,2023,3100302,Abre Campo,0.0,28.6
28400,2023,3100401,Acaiaca,0.0,40.0
28413,2023,3100500,Açucena,0.0,7.2

In [58]:
print("Anos encontrados:", df_rcd_final["ANO"].unique())

print("\nValores ausentes por coluna:")
print(df_rcd_final.isna().sum())

print("\nRegistro de Frutal:")
df_rcd_final[
    df_rcd_final["NO_MUNICIPIO"].str.upper() == "FRUTAL"
]

Anos encontrados: [2023]

Valores ausentes por coluna:
ANO                                 0
CO_MUNICIPIO                        0
NO_MUNICIPIO                        0
PERC_DOCENTES_BAIXA_REGULARIDADE    0
PERC_DOCENTES_ALTA_REGULARIDADE     0
dtype: int64

Registro de Frutal:

,ANO,CO_MUNICIPIO,NO_MUNICIPIO,PERC_DOCENTES_BAIXA_REGULARIDADE,PERC_DOCENTES_ALTA_REGULARIDADE
31826,2023,3127107,Frutal,0.0,4.3

In [60]:
df_rcd_final.to_csv(
    "rcd_mg_2023_tratado.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Arquivo salvo com sucesso.")

Arquivo salvo com sucesso.

In [61]:
files.download("rcd_mg_2023_tratado.csv")

## 5. Taxas de Rendimento Escolar

Nesta seção será realizada a leitura, inspeção e preparação da base de Taxas de Rendimento Escolar de 2023.

Essa base será utilizada para obter a variável-alvo do projeto: a Taxa de Abandono Escolar nos Anos Finais do Ensino Fundamental.

A base original será preservada sem alterações. O tratamento será realizado em uma cópia dos dados, considerando o recorte dos municípios de Minas Gerais e da rede pública.

In [62]:
url_rendimento = (
    "https://raw.githubusercontent.com/"
    "RaniellyPatricia/predicao-abandono-escolar-mg/"
    "main/data/raw/2023/rendimento/tx_rend_municipios_2023.xlsx"
)

resposta_rendimento = requests.get(url_rendimento)
resposta_rendimento.raise_for_status()

print("Tamanho baixado:", len(resposta_rendimento.content), "bytes")
print("Assinatura do arquivo:", resposta_rendimento.content[:4])

arquivo_rendimento = pd.ExcelFile(BytesIO(resposta_rendimento.content))

arquivo_rendimento.sheet_names

Tamanho baixado: 18744825 bytes
Assinatura do arquivo: b'PK\x03\x04'

['MUNICIPIOS ']

In [64]:
df_rendimento = pd.read_excel(
    BytesIO(resposta_rendimento.content),
    sheet_name="MUNICIPIOS ",
    header=8
)

print("Quantidade de linhas:", df_rendimento.shape[0])
print("Quantidade de colunas:", df_rendimento.shape[1])

df_rendimento.head()

Quantidade de linhas: 65630
Quantidade de colunas: 61

,NU_ANO_CENSO,NO_REGIAO,SG_UF,CO_MUNICIPIO,NO_MUNICIPIO,NO_CATEGORIA,NO_DEPENDENCIA,1_CAT_FUN,1_CAT_FUN_AI,1_CAT_FUN_AF,...,3_CAT_FUN_06,3_CAT_FUN_07,3_CAT_FUN_08,3_CAT_FUN_09,3_CAT_MED,3_CAT_MED_01,3_CAT_MED_02,3_CAT_MED_03,3_CAT_MED_04,3_CAT_MED_NS
0,2023,Norte,RO,1100015.0,Alta Floresta D'Oeste,Total,Total,93.1,93,93.2,...,0.5,0.6,2.7,1.5,0.4,0.6,0.4,0,--,--
1,2023,Norte,RO,1100015.0,Alta Floresta D'Oeste,Urbana,Total,93.5,93.7,93.3,...,0,0.6,3.1,1.6,0.3,0.8,0,0,--,--
2,2023,Norte,RO,1100015.0,Alta Floresta D'Oeste,Rural,Total,91.4,90.2,92.7,...,3.2,0,0,1.5,2,0,7.7,--,--,--
3,2023,Norte,RO,1100015.0,Alta Floresta D'Oeste,Total,Estadual,94.9,90,95.6,...,0,0,0.4,0.7,0.4,0.6,0.4,0,--,--
4,2023,Norte,RO,1100015.0,Alta Floresta D'Oeste,Urbana,Estadual,96.5,100,96.4,...,0,0,0.4,0.8,0.3,0.8,0,0,--,--

In [65]:
print("Colunas da base de rendimento:")

for coluna in df_rendimento.columns:
    print(coluna)

Colunas da base de rendimento:
NU_ANO_CENSO
NO_REGIAO
SG_UF
CO_MUNICIPIO
NO_MUNICIPIO
NO_CATEGORIA
NO_DEPENDENCIA
1_CAT_FUN
1_CAT_FUN_AI
1_CAT_FUN_AF
1_CAT_FUN_01
1_CAT_FUN_02
1_CAT_FUN_03
1_CAT_FUN_04
1_CAT_FUN_05
1_CAT_FUN_06
1_CAT_FUN_07
1_CAT_FUN_08
1_CAT_FUN_09
1_CAT_MED
1_CAT_MED_01
1_CAT_MED_02
1_CAT_MED_03
1_CAT_MED_04
1_CAT_MED_NS
2_CAT_FUN
2_CAT_FUN_AI
2_CAT_FUN_AF
2_CAT_FUN_01
2_CAT_FUN_02
2_CAT_FUN_03
2_CAT_FUN_04
2_CAT_FUN_05
2_CAT_FUN_06
2_CAT_FUN_07
2_CAT_FUN_08
2_CAT_FUN_09
2_CAT_MED
2_CAT_MED_01
2_CAT_MED_02
2_CAT_MED_03
2_CAT_MED_04
2_CAT_MED_NS
3_CAT_FUN
3_CAT_FUN_AI
3_CAT_FUN_AF
3_CAT_FUN_01
3_CAT_FUN_02
3_CAT_FUN_03
3_CAT_FUN_04
3_CAT_FUN_05
3_CAT_FUN_06
3_CAT_FUN_07
3_CAT_FUN_08
3_CAT_FUN_09
3_CAT_MED
3_CAT_MED_01
3_CAT_MED_02
3_CAT_MED_03
3_CAT_MED_04
3_CAT_MED_NS

In [66]:
df_rendimento_tratado = df_rendimento[
    df_rendimento["SG_UF"] == "MG"
].copy()

print("Linhas da base original:", len(df_rendimento))
print("Linhas de Minas Gerais:", len(df_rendimento_tratado))
print(
    "Municípios únicos:",
    df_rendimento_tratado["CO_MUNICIPIO"].nunique()
)

Linhas da base original: 65630
Linhas de Minas Gerais: 9470
Municípios únicos: 853

In [67]:
print("Valores de NO_CATEGORIA:")
print(df_rendimento_tratado["NO_CATEGORIA"].dropna().unique())

print("\nValores de NO_DEPENDENCIA:")
print(df_rendimento_tratado["NO_DEPENDENCIA"].dropna().unique())

Valores de NO_CATEGORIA:
['Total' 'Urbana' 'Rural']

Valores de NO_DEPENDENCIA:
['Total' 'Estadual' 'Municipal' 'Pública' 'Privada' 'Federal']

In [68]:
df_rendimento_tratado = df_rendimento_tratado[
    (df_rendimento_tratado["NO_CATEGORIA"] == "Total") &
    (df_rendimento_tratado["NO_DEPENDENCIA"] == "Pública")
].copy()

print("Quantidade de linhas:", len(df_rendimento_tratado))
print(
    "Quantidade de municípios únicos:",
    df_rendimento_tratado["CO_MUNICIPIO"].nunique()
)

Quantidade de linhas: 853
Quantidade de municípios únicos: 853

In [69]:
print(
    "Valores ausentes em 3_CAT_FUN_AF:",
    df_rendimento_tratado["3_CAT_FUN_AF"].isna().sum()
)

print(
    "Tipo da coluna:",
    df_rendimento_tratado["3_CAT_FUN_AF"].dtype
)

df_rendimento_tratado[
    ["CO_MUNICIPIO", "NO_MUNICIPIO", "3_CAT_FUN_AF"]
].head()

Valores ausentes em 3_CAT_FUN_AF: 0
Tipo da coluna: object

       CO_MUNICIPIO         NO_MUNICIPIO 3_CAT_FUN_AF
28435     3100104.0  Abadia dos Dourados          2.2
28448     3100203.0               Abaeté          0.7
28460     3100302.0           Abre Campo          1.1
28473     3100401.0              Acaiaca            0
28485     3100500.0              Açucena          1.7

In [70]:
df_rendimento_tratado["3_CAT_FUN_AF"] = pd.to_numeric(
    df_rendimento_tratado["3_CAT_FUN_AF"],
    errors="coerce"
)

print("Novo tipo:", df_rendimento_tratado["3_CAT_FUN_AF"].dtype)
print("Valores ausentes:", df_rendimento_tratado["3_CAT_FUN_AF"].isna().sum())
print("Menor taxa de abandono:", df_rendimento_tratado["3_CAT_FUN_AF"].min())
print("Maior taxa de abandono:", df_rendimento_tratado["3_CAT_FUN_AF"].max())

Novo tipo: float64
Valores ausentes: 0
Menor taxa de abandono: 0.0
Maior taxa de abandono: 9.3

In [71]:
df_rendimento_final = df_rendimento_tratado[
    [
        "NU_ANO_CENSO",
        "CO_MUNICIPIO",
        "NO_MUNICIPIO",
        "3_CAT_FUN_AF"
    ]
].copy()

df_rendimento_final = df_rendimento_final.rename(
    columns={
        "NU_ANO_CENSO": "ANO",
        "3_CAT_FUN_AF": "TAXA_ABANDONO_ANOS_FINAIS"
    }
)

df_rendimento_final["CO_MUNICIPIO"] = (
    df_rendimento_final["CO_MUNICIPIO"].astype("int64")
)

print("Quantidade de linhas:", len(df_rendimento_final))
print(
    "Municípios duplicados:",
    df_rendimento_final["CO_MUNICIPIO"].duplicated().sum()
)

df_rendimento_final.head()

Quantidade de linhas: 853
Municípios duplicados: 0

        ANO  CO_MUNICIPIO         NO_MUNICIPIO  TAXA_ABANDONO_ANOS_FINAIS
28435  2023       3100104  Abadia dos Dourados                        2.2
28448  2023       3100203               Abaeté                        0.7
28460  2023       3100302           Abre Campo                        1.1
28473  2023       3100401              Acaiaca                        0.0
28485  2023       3100500              Açucena                        1.7

In [73]:
print("Anos encontrados:", df_rendimento_final["ANO"].unique())

print("\nValores ausentes por coluna:")
print(df_rendimento_final.isna().sum())

print("\nRegistro de Frutal:")
df_rendimento_final[
    df_rendimento_final["NO_MUNICIPIO"].str.upper() == "FRUTAL"
]

Anos encontrados: [2023]

Valores ausentes por coluna:
ANO                          0
CO_MUNICIPIO                 0
NO_MUNICIPIO                 0
TAXA_ABANDONO_ANOS_FINAIS    0
dtype: int64

Registro de Frutal:

        ANO  CO_MUNICIPIO NO_MUNICIPIO  TAXA_ABANDONO_ANOS_FINAIS
31794  2023       3127107       Frutal                        1.5

In [75]:
df_rendimento_final.to_csv(
    "rendimento_mg_2023_tratado.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Arquivo salvo com sucesso.")

Arquivo salvo com sucesso.

In [76]:
files.download("rendimento_mg_2023_tratado.csv")